require 'hammer_cli_foreman_ansible/command_extensions/resolver'
require 'hammer_cli_foreman_ansible/command_extensions/inventory'
require 'hammer_cli_foreman_ansible/command_extensions/job_template'
